/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Clases.CambiarPanel;
import Clases.SqlUsuarios;
import Ventanas.Registro1;
import static Ventanas.Registro1.LB_Pnl;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author janie
 */
public class Registro2 extends javax.swing.JPanel {

    /**
     * Creates new form Registro2
     */
    int codAleat;

    public Registro2() {
        initComponents();
        LB_Pnl.setText("Datos de la cuenta");
    }

    private void limpiarRegistro() {
        TF_Código.setText("");
        Paneles.Registro.TF_PNombre.setText("");
        Paneles.Registro.TF_SNombre.setText("");
        Paneles.Registro.TF_PApellido.setText("");
        Paneles.Registro.TF_SNombre.setText("");
        TF_Correo.setText("");
        Paneles.Registro.TF_Dire.setText("");
        Paneles.Registro.TF_Telefono.setText("");
        TF_Contra.setText("");
        CB_Perfil.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF_Contra = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel5 = new javax.swing.JLabel();
        TF_Correo = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel3 = new javax.swing.JLabel();
        CB_Perfil = new rojerusan.RSComboMetro();
        Teléfono = new javax.swing.JLabel();
        TF_Código = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel2 = new javax.swing.JLabel();
        BT_Codigo = new javax.swing.JButton();
        BT_Return = new rojerusan.RSButtonRound();
        BT_Finalizar = new rojerusan.RSButtonRound();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF_Contra.setForeground(new java.awt.Color(173, 204, 188));
        TF_Contra.setToolTipText("Digite un código...");
        TF_Contra.setBorderColor(new java.awt.Color(173, 204, 188));
        TF_Contra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TF_Contra.setPhColor(new java.awt.Color(84, 100, 92));
        TF_Contra.setPlaceholder("Digite un código...");
        add(TF_Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 166, -1));

        jLabel5.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel5.setText("Contraseña");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 29));

        TF_Correo.setForeground(new java.awt.Color(173, 204, 188));
        TF_Correo.setToolTipText("Digite un código...");
        TF_Correo.setBorderColor(new java.awt.Color(173, 204, 188));
        TF_Correo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TF_Correo.setPhColor(new java.awt.Color(84, 100, 92));
        TF_Correo.setPlaceholder("Digite un código...");
        add(TF_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 166, -1));

        jLabel3.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel3.setText("Correo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 29));

        CB_Perfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione uno...", "Administrador", "Usuario" }));
        CB_Perfil.setColorArrow(new java.awt.Color(74, 141, 124));
        CB_Perfil.setColorBorde(new java.awt.Color(74, 141, 124));
        CB_Perfil.setColorFondo(new java.awt.Color(173, 204, 188));
        CB_Perfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(CB_Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 210, 40));

        Teléfono.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        Teléfono.setText("Tipo de perfil");
        add(Teléfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, 29));

        TF_Código.setForeground(new java.awt.Color(173, 204, 188));
        TF_Código.setToolTipText("Digite un código...");
        TF_Código.setBorderColor(new java.awt.Color(173, 204, 188));
        TF_Código.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TF_Código.setPhColor(new java.awt.Color(84, 100, 92));
        TF_Código.setPlaceholder("Digite un código...");
        add(TF_Código, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 166, -1));

        jLabel2.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel2.setText("Código");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 29));

        BT_Codigo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        BT_Codigo.setForeground(new java.awt.Color(102, 102, 102));
        BT_Codigo.setText("Generar código aleatorio");
        BT_Codigo.setBorderPainted(false);
        BT_Codigo.setContentAreaFilled(false);
        BT_Codigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Codigo.setFocusPainted(false);
        BT_Codigo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BT_CodigoMouseMoved(evt);
            }
        });
        BT_Codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BT_CodigoMouseExited(evt);
            }
        });
        BT_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CodigoActionPerformed(evt);
            }
        });
        add(BT_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 210, 40));

        BT_Return.setBackground(new java.awt.Color(74, 141, 124));
        BT_Return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/return.png"))); // NOI18N
        BT_Return.setText("Regresar");
        BT_Return.setColorHover(new java.awt.Color(173, 204, 188));
        BT_Return.setFont(new java.awt.Font("Keep Calm Med", 0, 18)); // NOI18N
        BT_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ReturnActionPerformed(evt);
            }
        });
        add(BT_Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 210, -1));

        BT_Finalizar.setBackground(new java.awt.Color(74, 141, 124));
        BT_Finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        BT_Finalizar.setText("Finalizar");
        BT_Finalizar.setColorHover(new java.awt.Color(173, 204, 188));
        BT_Finalizar.setFont(new java.awt.Font("Keep Calm Med", 0, 18)); // NOI18N
        BT_Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_FinalizarActionPerformed(evt);
            }
        });
        add(BT_Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BT_CodigoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_CodigoMouseMoved
        BT_Codigo.setForeground(new Color(0, 204, 204));
    }//GEN-LAST:event_BT_CodigoMouseMoved

    private void BT_CodigoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_CodigoMouseExited
        BT_Codigo.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_BT_CodigoMouseExited

    private void BT_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CodigoActionPerformed
        codAleat = (int) (Math.random() * 999999) + 1;
        TF_Código.setText(codAleat + "");
    }//GEN-LAST:event_BT_CodigoActionPerformed

    private void BT_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ReturnActionPerformed
        new CambiarPanel(Registro1.pnlPrincipal, new Registro());
    }//GEN-LAST:event_BT_ReturnActionPerformed

    private void BT_FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_FinalizarActionPerformed
        if (!SqlUsuarios.verficarUsuario(TF_Código.getText())) {
            int opcion = SqlUsuarios.guardarUsuario();
            if (opcion > 0) {
                JOptionPane.showMessageDialog(null, "El registro ha sido éxitoso");
                SqlUsuarios.listarUsuario("");
                limpiarRegistro();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar este usuario");
                limpiarRegistro();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Hacen falta algunos datos.");

        }
        Registro1 registro = new Registro1();
        registro.dispose();
    }//GEN-LAST:event_BT_FinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Codigo;
    private rojerusan.RSButtonRound BT_Finalizar;
    private rojerusan.RSButtonRound BT_Return;
    public static rojerusan.RSComboMetro CB_Perfil;
    public static rojerusan.RSMetroTextFullPlaceHolder TF_Contra;
    public static rojerusan.RSMetroTextFullPlaceHolder TF_Correo;
    public static rojerusan.RSMetroTextFullPlaceHolder TF_Código;
    private javax.swing.JLabel Teléfono;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
