package Ventanas;

import Clases.CambiarPanel;
import Clases.SqlUsuarios;
import rojerusan.RSNotifyShadowAnimated;

public class EditarUsuario extends javax.swing.JFrame {

    int x;
    int y;

    public EditarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Barra = new javax.swing.JPanel();
        BT_Salir = new javax.swing.JButton();
        BT_minimizar = new javax.swing.JButton();
        Panel_Fondo = new javax.swing.JPanel();
        pnlCentro = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        LB_Pnl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTFPnombre = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFSnombre = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel6 = new javax.swing.JLabel();
        jTFSapellido = new rojerusan.RSMetroTextFullPlaceHolder();
        jTFPapellido = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFtelefono = new rojerusan.RSMetroTextFullPlaceHolder();
        jTFdireccion = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFcorreo = new rojerusan.RSMetroTextFullPlaceHolder();
        jTFpassword = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel10 = new javax.swing.JLabel();
        Teléfono = new javax.swing.JLabel();
        jCBperfil = new rojerusan.RSComboMetro();
        BT_Finalizar = new rojerusan.RSButtonRound();
        jLabel11 = new javax.swing.JLabel();
        jTFcodigo = new rojerusan.RSMetroTextFullPlaceHolder();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Barra.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_BarraMouseDragged(evt);
            }
        });
        Panel_Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_BarraMousePressed(evt);
            }
        });

        BT_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarPeque.png"))); // NOI18N
        BT_Salir.setToolTipText("Cerrar");
        BT_Salir.setBorderPainted(false);
        BT_Salir.setContentAreaFilled(false);
        BT_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_SalirMouseClicked(evt);
            }
        });
        BT_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SalirActionPerformed(evt);
            }
        });

        BT_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimize.png"))); // NOI18N
        BT_minimizar.setToolTipText("Minimizar");
        BT_minimizar.setBorderPainted(false);
        BT_minimizar.setContentAreaFilled(false);
        BT_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_minimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_BarraLayout = new javax.swing.GroupLayout(Panel_Barra);
        Panel_Barra.setLayout(Panel_BarraLayout);
        Panel_BarraLayout.setHorizontalGroup(
            Panel_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BarraLayout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(BT_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BT_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel_BarraLayout.setVerticalGroup(
            Panel_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BT_Salir)
            .addComponent(BT_minimizar)
        );

        getContentPane().add(Panel_Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, -1));

        Panel_Fondo.setBackground(new java.awt.Color(49, 83, 48));

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(49, 83, 48));

        LB_Pnl.setFont(new java.awt.Font("Keep Calm Med", 0, 18)); // NOI18N
        LB_Pnl.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_Pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LB_Pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(pnlPrincipal);

        jLabel8.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Editar");

        jTFPnombre.setForeground(new java.awt.Color(173, 204, 188));
        jTFPnombre.setToolTipText("Digite su primer nombre...");
        jTFPnombre.setBorderColor(new java.awt.Color(173, 204, 188));
        jTFPnombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFPnombre.setPhColor(new java.awt.Color(84, 100, 92));

        jLabel3.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel3.setText("Primer Nombre");

        jLabel4.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel4.setText("Segundo Nombre");

        jTFSnombre.setForeground(new java.awt.Color(173, 204, 188));
        jTFSnombre.setToolTipText("Digite su segundo nombre...");
        jTFSnombre.setBorderColor(new java.awt.Color(173, 204, 188));
        jTFSnombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFSnombre.setPhColor(new java.awt.Color(84, 100, 92));

        jLabel6.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel6.setText("Segundo Apellido");

        jTFSapellido.setForeground(new java.awt.Color(173, 204, 188));
        jTFSapellido.setToolTipText("Digite su segundo apellido...");
        jTFSapellido.setBorderColor(new java.awt.Color(173, 204, 188));
        jTFSapellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFSapellido.setPhColor(new java.awt.Color(84, 100, 92));

        jTFPapellido.setForeground(new java.awt.Color(173, 204, 188));
        jTFPapellido.setToolTipText("Digite su primer apellido...");
        jTFPapellido.setBorderColor(new java.awt.Color(173, 204, 188));
        jTFPapellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFPapellido.setPhColor(new java.awt.Color(84, 100, 92));

        jLabel5.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel5.setText("Primer Apellido");

        jLabel9.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel9.setText("Teléfono");

        jTFtelefono.setForeground(new java.awt.Color(173, 204, 188));
        jTFtelefono.setToolTipText("Digite su teléfono...");
        jTFtelefono.setBorderColor(new java.awt.Color(173, 204, 188));
        jTFtelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFtelefono.setPhColor(new java.awt.Color(84, 100, 92));

        jTFdireccion.setForeground(new java.awt.Color(173, 204, 188));
        jTFdireccion.setToolTipText("Digite su dirección...");
        jTFdireccion.setBorderColor(new java.awt.Color(173, 204, 188));
        jTFdireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFdireccion.setPhColor(new java.awt.Color(84, 100, 92));

        jLabel7.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel7.setText("Dirección");

        jLabel2.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel2.setText("Correo");

        jTFcorreo.setForeground(new java.awt.Color(173, 204, 188));
        jTFcorreo.setToolTipText("Digite su teléfono...");
        jTFcorreo.setBorderColor(new java.awt.Color(173, 204, 188));
        jTFcorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFcorreo.setPhColor(new java.awt.Color(84, 100, 92));

        jTFpassword.setForeground(new java.awt.Color(173, 204, 188));
        jTFpassword.setToolTipText("Digite su teléfono...");
        jTFpassword.setBorderColor(new java.awt.Color(173, 204, 188));
        jTFpassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFpassword.setPhColor(new java.awt.Color(84, 100, 92));

        jLabel10.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel10.setText("Contrseña");

        Teléfono.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        Teléfono.setText("Tipo de perfil");

        jCBperfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione uno...", "Administrador", "Usuario" }));
        jCBperfil.setColorArrow(new java.awt.Color(74, 141, 124));
        jCBperfil.setColorBorde(new java.awt.Color(74, 141, 124));
        jCBperfil.setColorFondo(new java.awt.Color(173, 204, 188));
        jCBperfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        BT_Finalizar.setBackground(new java.awt.Color(74, 141, 124));
        BT_Finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        BT_Finalizar.setText("Regostrar");
        BT_Finalizar.setColorHover(new java.awt.Color(173, 204, 188));
        BT_Finalizar.setFont(new java.awt.Font("Keep Calm Med", 0, 18)); // NOI18N
        BT_Finalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_FinalizarMouseClicked(evt);
            }
        });
        BT_Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_FinalizarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel11.setText("Codigo");

        jTFcodigo.setForeground(new java.awt.Color(173, 204, 188));
        jTFcodigo.setToolTipText("Digite su primer nombre...");
        jTFcodigo.setBorderColor(new java.awt.Color(173, 204, 188));
        jTFcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFcodigo.setPhColor(new java.awt.Color(84, 100, 92));
        jTFcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcodigoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_1.png"))); // NOI18N
        jButton1.setToolTipText("Buscar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentroLayout.createSequentialGroup()
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCentroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCentroLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCentroLayout.createSequentialGroup()
                                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFPnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFPapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGap(80, 80, 80)
                                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jTFSnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jTFSapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(jTFdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentroLayout.createSequentialGroup()
                                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Teléfono)
                                                    .addGroup(pnlCentroLayout.createSequentialGroup()
                                                        .addComponent(jCBperfil, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                                        .addGap(80, 80, 80)
                                                        .addComponent(BT_Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTFcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(80, 80, 80)
                                                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jTFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCentroLayout.createSequentialGroup()
                                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCentroLayout.createSequentialGroup()
                                        .addComponent(jTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentroLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentroLayout.createSequentialGroup()
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFPnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFPapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Teléfono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))))
        );

        javax.swing.GroupLayout Panel_FondoLayout = new javax.swing.GroupLayout(Panel_Fondo);
        Panel_Fondo.setLayout(Panel_FondoLayout);
        Panel_FondoLayout.setHorizontalGroup(
            Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_FondoLayout.setVerticalGroup(
            Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 540, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_SalirMouseClicked
        this.dispose();

    }//GEN-LAST:event_BT_SalirMouseClicked

    private void BT_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_minimizarMouseClicked
        this.setState(Riego.ICONIFIED);
        this.BT_minimizar.setSelected(false);
    }//GEN-LAST:event_BT_minimizarMouseClicked

    private void Panel_BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_BarraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_Panel_BarraMouseDragged

    private void Panel_BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_BarraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_Panel_BarraMousePressed

    private void BT_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_SalirActionPerformed

    private void BT_FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_FinalizarActionPerformed
        
    }//GEN-LAST:event_BT_FinalizarActionPerformed

    private void jTFcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcodigoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        SqlUsuarios.buscarUsuario();
    }//GEN-LAST:event_jButton1MouseClicked

    private void BT_FinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_FinalizarMouseClicked
        SqlUsuarios.modificar();
        new rojerusan.RSNotifyShadowAnimated("!Hecho¡",
           "!Se ha actualizado correctamente!", 
           3, 
           RSNotifyShadowAnimated.PositionNotify.BottomLeft, 
           RSNotifyShadowAnimated.AnimationNotify.LeftRight, 
           RSNotifyShadowAnimated.TypeNotify.SUCCESS).setVisible(true); 
        SqlUsuarios.listarUsuario("");
    }//GEN-LAST:event_BT_FinalizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonRound BT_Finalizar;
    private javax.swing.JButton BT_Salir;
    private javax.swing.JButton BT_minimizar;
    public static javax.swing.JLabel LB_Pnl;
    private javax.swing.JPanel Panel_Barra;
    public static javax.swing.JPanel Panel_Fondo;
    private javax.swing.JLabel Teléfono;
    private javax.swing.JButton jButton1;
    public static rojerusan.RSComboMetro jCBperfil;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static rojerusan.RSMetroTextFullPlaceHolder jTFPapellido;
    public static rojerusan.RSMetroTextFullPlaceHolder jTFPnombre;
    public static rojerusan.RSMetroTextFullPlaceHolder jTFSapellido;
    public static rojerusan.RSMetroTextFullPlaceHolder jTFSnombre;
    public static rojerusan.RSMetroTextFullPlaceHolder jTFcodigo;
    public static rojerusan.RSMetroTextFullPlaceHolder jTFcorreo;
    public static rojerusan.RSMetroTextFullPlaceHolder jTFdireccion;
    public static rojerusan.RSMetroTextFullPlaceHolder jTFpassword;
    public static rojerusan.RSMetroTextFullPlaceHolder jTFtelefono;
    public static javax.swing.JPanel pnlCentro;
    public static javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
